### ISSUE TITLE
Google: Your Sitemap or Sitemap index file doesn't properly declare the namespace.

### ISSUE THREAD

**Issue by fillon** [ThePixelDeveloper/Sitemap#46] opened 2017-07-30 23:25 UTC
Hi,

Since the last release, Google Console is complaining about the namespaces using https.

--
Your Sitemap or Sitemap index file doesn't properly declare the namespace. Expected: http://www.w3.org/1999/xhtml Found: https://www.w3.org/1999/xhtml
Parent tag: url
Tag: link
--

**Comment by ThePixelDeveloper** [comment] 2017-07-31 08:20
Thanks for the report, will take a look today.

**Comment by terales** [comment] 2017-08-07 17:01
I think it's connected with an implementation of #43

**Comment by NeilMasters** [comment] 2017-09-01 08:23
We are receiving this exact error and I believe the issue is related to my fix : https://github.com/ThePixelDeveloper/Sitemap/pull/48

The address is not actually uri but a schema reference in the format of a uri and discussed in official docs as a uri reference which leads to nothing but confusion.

https://www.w3.org/TR/xhtml1-schema/

**Comment by hotrush** [comment] 2017-09-13 09:05
@ThePixelDeveloper any plans to merge this?

**Comment by mikerockett** [comment] 2017-09-14 16:56
Given this error, which I'm also going to land up experiencing in the development of rockettpw/markup-sitemap for ProcessWire, does it actually make a difference in rankings? Can the error be ignored?

**Comment by hotrush** [comment] 2017-09-14 19:45
@mikerockett google just abandoned my sitemap with this error

**Comment by mikerockett** [comment] 2017-09-14 20:05
@hotrush That sucks. Seems like such a rudimentary thing that doesn't make much of a difference, especially considering the https-everywhere concept that they love oh-so-much.

@ThePixelDeveloper, please can we have #48 merged? Not sure on the TCI failures...

**Comment by terales** [comment] 2017-09-14 21:03
Could you fix test suite? It looks like #48 ruins some test

**Comment by mikerockett** [comment] 2017-09-14 21:08
@terales I'll have a look tomorrow. Hoping it's a minor thing...

**Comment by mikerockett** [comment] 2017-09-15 06:09
The diff engine is showing the the output is different, but they're identical. Not a phpspec user, so not sure what's going on here.

```
@@ -1,10 +1,10 @@
-<?xml version="1.0" encoding="UTF-8"?>
-<?xml-stylesheet type="text/xsl" href="/path/to/xslt/main-sitemap.xsl"?>
-<urlset xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.sitemaps.org/schemas/sitemap/0.9 https://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd" xmlns="https://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="https://www.w3.org/1999/xhtml">
-    <url>
-        <loc>https://www.example.com/english/</loc>
-        <xhtml:link rel="alternate" hreflang="de" href="https://www.example.com/deutsch/"/>
-        <xhtml:link rel="alternate" hreflang="de-ch" href="https://www.example.com/schweiz-deutsch/"/>
-        <xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/english/"/>
-    </url>
+<?xml version="1.0" encoding="UTF-8"?>
+<?xml-stylesheet type="text/xsl" href="/path/to/xslt/main-sitemap.xsl"?>
+<urlset xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.sitemaps.org/schemas/sitemap/0.9 https://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd" xmlns="https://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="https://www.w3.org/1999/xhtml">
+    <url>
+        <loc>https://www.example.com/english/</loc>
+        <xhtml:link rel="alternate" hreflang="de" href="https://www.example.com/deutsch/"/>
+        <xhtml:link rel="alternate" hreflang="de-ch" href="https://www.example.com/schweiz-deutsch/"/>
+        <xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/english/"/>
+    </url>
 </urlset>
```

**Closed** 2017-09-17 19:33 UTC
Labels: bug
